-- Train the ANN on the data generated by frequencies.lua
--
-- Create a new standard neural net with:
-- 26 neurons in layer 1 (input)
-- 13 neurons in layer 2
-- 3  neurons in layer 3 (output)
--
net=fann.Net.create_standard({26,13,3})

-- Train the net on the file train.data, generated by frequencies.lua
-- 20000 maximum number of epochs
-- 10 interval between reporting
-- 0.0001 desired error on test data
net:train_on_file("train.data",20000,10,0.0001)

-- Save the obtained net to this file.
net:save("language_clas.net")
